export type Category = 'Backend' | 'Frontend' | 'Datos' | 'DevTools' | 'IA' | 'Testing'
export type Library = { name:string; category:Category; description:string; tags:string[]; downloads:string; weeklyDownloads:number; stars:string; npm:string; github:string; color:string; featured?:boolean }
type Seed = [string, Category, string, string, string, string[]]
const palette=['#ff795f','#a48cff','#d8ff63','#61c9ff','#ff87b7','#75e5be']
const catalogue: Seed[] = [
  ['Hono','Backend','Framework web rápido basado en estándares para Node, edge y más.','hono','honojs/hono',['Edge','TypeScript']],
  ['Fastify','Backend','Framework HTTP de alto rendimiento y extensible.','fastify','fastify/fastify',['HTTP','Plugins']],
  ['Express','Backend','El clásico minimalista para APIs y servidores Node.js.','express','expressjs/express',['HTTP','Middleware']],
  ['NestJS','Backend','Framework modular para aplicaciones de servidor escalables.','@nestjs/core','nestjs/nest',['DI','Enterprise']],
  ['Koa','Backend','Middleware moderno y elegante para Node.js.','koa','koajs/koa',['Async','Middleware']],
  ['Elysia','Backend','Framework TypeScript de alto rendimiento para Bun.','elysia','elysiajs/elysia',['Bun','Type-safe']],
  ['AdonisJS','Backend','Framework full-stack TypeScript con enfoque productivo.','@adonisjs/core','adonisjs/core',['MVC','Full-stack']],
  ['tRPC','Backend','APIs end-to-end type-safe sin generación de código.','@trpc/server','trpc/trpc',['RPC','Type-safe']],
  ['Socket.IO','Backend','Comunicación bidireccional basada en eventos.','socket.io','socketio/socket.io',['Realtime','WebSocket']],
  ['Apollo Server','Backend','Servidor GraphQL con herramientas de producción.','@apollo/server','apollographql/apollo-server',['GraphQL','API']],
  ['GraphQL Yoga','Backend','Servidor GraphQL sencillo y compatible con estándares.','graphql-yoga','dotansimha/graphql-yoga',['GraphQL','Fetch']],
  ['BullMQ','Backend','Colas robustas de trabajos sobre Redis.','bullmq','taskforcesh/bullmq',['Queues','Redis']],
  ['Pino','Backend','Logger JSON muy rápido para Node.js.','pino','pinojs/pino',['Logging','JSON']],
  ['Winston','Backend','Logger flexible con múltiples transportes.','winston','winstonjs/winston',['Logging','Transports']],
  ['Passport','Backend','Autenticación modular para Node.js.','passport','jaredhanson/passport',['Auth','Strategies']],
  ['Multer','Backend','Middleware para procesar formularios multipart.','multer','expressjs/multer',['Uploads','Express']],
  ['Swagger UI Express','Backend','Documentación OpenAPI interactiva para Express.','swagger-ui-express','scottie1984/swagger-ui-express',['OpenAPI','Docs']],
  ['React','Frontend','La biblioteca declarativa para interfaces de usuario.','react','facebook/react',['UI','Components']],
  ['Next.js','Frontend','Framework React para aplicaciones web completas.','next','vercel/next.js',['React','Full-stack']],
  ['Vite','Frontend','Herramienta de desarrollo frontend ultrarrápida.','vite','vitejs/vite',['Build','HMR']],
  ['TanStack Query','Frontend','Estado remoto, cache y sincronización de datos.','@tanstack/react-query','TanStack/query',['Cache','Async state']],
  ['TanStack Router','Frontend','Router type-safe y potente para React.','@tanstack/react-router','TanStack/router',['Routing','Type-safe']],
  ['Zustand','Frontend','Gestión de estado minimalista basada en hooks.','zustand','pmndrs/zustand',['State','Hooks']],
  ['Redux Toolkit','Frontend','La forma recomendada de trabajar con Redux.','@reduxjs/toolkit','reduxjs/redux-toolkit',['State','Redux']],
  ['Jotai','Frontend','Átomos primitivos y flexibles para estado React.','jotai','pmndrs/jotai',['State','Atoms']],
  ['React Hook Form','Frontend','Formularios performantes y con pocos renders.','react-hook-form','react-hook-form/react-hook-form',['Forms','Hooks']],
  ['Radix UI','Frontend','Primitivas accesibles sin estilos para React.','@radix-ui/react-dialog','radix-ui/primitives',['A11y','Primitives']],
  ['shadcn/ui','Frontend','Componentes reutilizables construidos sobre Radix.','shadcn-ui','shadcn-ui/ui',['Components','Radix']],
  ['Tailwind CSS','Frontend','CSS utility-first para diseño rápido y consistente.','tailwindcss','tailwindlabs/tailwindcss',['CSS','Utilities']],
  ['Framer Motion','Frontend','Animaciones declarativas para React.','framer-motion','motiondivision/motion',['Animation','Motion']],
  ['React Router','Frontend','Enrutamiento declarativo para aplicaciones React.','react-router','remix-run/react-router',['Routing','React']],
  ['Zod','DevTools','Validación de esquemas con inferencia TypeScript.','zod','colinhacks/zod',['Validation','Schemas']],
  ['Valibot','DevTools','Validación de esquemas modular y ligera.','valibot','fabian-hiller/valibot',['Validation','Lightweight']],
  ['TypeScript','DevTools','JavaScript con sintaxis para tipos estáticos.','typescript','microsoft/TypeScript',['Types','Language']],
  ['ESLint','DevTools','Analizador estático para encontrar problemas en código.','eslint','eslint/eslint',['Linting','Quality']],
  ['Prettier','DevTools','Formateador de código opinado.','prettier','prettier/prettier',['Formatting','Style']],
  ['Biome','DevTools','Toolchain web rápido para linting y formato.','@biomejs/biome','biomejs/biome',['Linting','Formatting']],
  ['tsup','DevTools','Bundler TypeScript sencillo basado en esbuild.','tsup','egoist/tsup',['Bundler','TypeScript']],
  ['tsx','DevTools','Ejecutor TypeScript rápido para Node.js.','tsx','privatenumber/tsx',['Runtime','TypeScript']],
  ['ts-node','DevTools','Entorno de ejecución TypeScript para Node.','ts-node','TypeStrong/ts-node',['Runtime','REPL']],
  ['Turbo','DevTools','Sistema de builds incremental para monorepos.','turbo','vercel/turborepo',['Monorepo','Build']],
  ['Nx','DevTools','Plataforma de construcción para repositorios grandes.','nx','nrwl/nx',['Monorepo','Build']],
  ['Husky','DevTools','Git hooks modernos y fáciles de configurar.','husky','typicode/husky',['Git','Hooks']],
  ['lint-staged','DevTools','Ejecuta linters sobre archivos preparados en Git.','lint-staged','lint-staged/lint-staged',['Git','Linting']],
  ['dotenv','DevTools','Carga variables de entorno desde archivos .env.','dotenv','motdotla/dotenv',['Config','Environment']],
  ['concurrently','DevTools','Ejecuta varios comandos npm en paralelo.','concurrently','open-cli-tools/concurrently',['CLI','Scripts']],
  ['Drizzle ORM','Datos','ORM SQL ligero y type-safe para TypeScript.','drizzle-orm','drizzle-team/drizzle-orm',['SQL','ORM']],
  ['Prisma','Datos','Toolkit de base de datos con ORM type-safe.','prisma','prisma/prisma',['ORM','Migrations']],
  ['TypeORM','Datos','ORM maduro para TypeScript y JavaScript.','typeorm','typeorm/typeorm',['ORM','SQL']],
  ['Kysely','Datos','Query builder TypeScript con tipos de extremo a extremo.','kysely','kysely-org/kysely',['SQL','Query builder']],
  ['Knex','Datos','Query builder SQL flexible para Node.js.','knex','knex/knex',['SQL','Migrations']],
  ['Mongoose','Datos','Modelado de objetos elegante para MongoDB.','mongoose','Automattic/mongoose',['MongoDB','ODM']],
  ['Sequelize','Datos','ORM multi-dialecto para Node.js.','sequelize','sequelize/sequelize',['ORM','SQL']],
  ['Redis','Datos','Cliente Redis moderno y completo para Node.js.','redis','redis/node-redis',['Redis','Cache']],
  ['ioredis','Datos','Cliente Redis robusto con soporte cluster.','ioredis','redis/ioredis',['Redis','Cluster']],
  ['pg','Datos','Cliente PostgreSQL para Node.js.','pg','brianc/node-postgres',['Postgres','Driver']],
  ['MongoDB','Datos','Driver oficial de MongoDB para Node.js.','mongodb','mongodb/node-mongodb-native',['MongoDB','Driver']],
  ['better-sqlite3','Datos','Driver SQLite síncrono y de alto rendimiento.','better-sqlite3','WiseLibs/better-sqlite3',['SQLite','Driver']],
  ['Supabase JS','Datos','Cliente JavaScript oficial para Supabase.','@supabase/supabase-js','supabase/supabase-js',['Supabase','Postgres']],
  ['Vitest','Testing','Framework de tests rápido y compatible con Vite.','vitest','vitest-dev/vitest',['Unit tests','Vite']],
  ['Playwright','Testing','Automatización fiable de navegadores multiplataforma.','playwright','microsoft/playwright',['E2E','Browser']],
  ['Cypress','Testing','Testing end-to-end para aplicaciones web.','cypress','cypress-io/cypress',['E2E','Browser']],
  ['Jest','Testing','Plataforma de testing JavaScript completa.','jest','jestjs/jest',['Unit tests','Mocks']],
  ['Testing Library','Testing','Utilidades de tests centradas en el usuario.','@testing-library/react','testing-library/react-testing-library',['React','A11y']],
  ['Supertest','Testing','Asserts HTTP para servidores Node.js.','supertest','ladjs/supertest',['HTTP','API']],
  ['MSW','Testing','Mocking de APIs por interceptación de red.','msw','mswjs/msw',['Mocking','Network']],
  ['Storybook','Testing','Taller visual para componentes de interfaz.','storybook','storybookjs/storybook',['Components','Visual']],
  ['k6','Testing','Testing de carga moderno para APIs y sistemas.','k6','grafana/k6',['Load testing','Performance']],
  ['Artillery','Testing','Testing de carga y rendimiento para aplicaciones.','artillery','artilleryio/artillery',['Load testing','API']],
  ['fast-check','Testing','Property-based testing para TypeScript.','fast-check','dubzzz/fast-check',['Property testing','Types']],
  ['Pact','Testing','Contract testing para microservicios.','@pact-foundation/pact','pact-foundation/pact-js',['Contracts','API']],
  ['LangChain','IA','Bloques para crear aplicaciones con modelos de lenguaje.','langchain','langchain-ai/langchainjs',['LLM','Agents']],
  ['Vercel AI SDK','IA','Toolkit TypeScript para interfaces y apps de IA.','ai','vercel/ai',['LLM','Streaming']],
  ['OpenAI SDK','IA','Cliente oficial de OpenAI para JavaScript.','openai','openai/openai-node',['OpenAI','API']],
  ['Anthropic SDK','IA','Cliente oficial de Anthropic para TypeScript.','@anthropic-ai/sdk','anthropics/anthropic-sdk-typescript',['Claude','API']],
  ['LlamaIndex','IA','Framework de datos para aplicaciones con LLMs.','llamaindex','run-llama/LlamaIndexTS',['RAG','Agents']],
  ['Mastra','IA','Framework TypeScript para agentes y workflows.','@mastra/core','mastra-ai/mastra',['Agents','Workflows']],
  ['Vercel AI Elements','IA','Componentes para experiencias de IA conversacional.','@ai-sdk/react','vercel/ai',['AI UI','React']],
  ['Transformers.js','IA','Modelos ML en el navegador y Node.js.','@huggingface/transformers','huggingface/transformers.js',['ML','Transformers']],
  ['TensorFlow.js','IA','Machine learning en JavaScript.','@tensorflow/tfjs','tensorflow/tfjs',['ML','TensorFlow']],
  ['Ollama','IA','Cliente JavaScript para modelos locales Ollama.','ollama','ollama/ollama-js',['Local LLM','API']],
  ['Pinecone','IA','Cliente Node.js para búsqueda vectorial Pinecone.','@pinecone-database/pinecone','pinecone-io/pinecone-ts-client',['Vectors','RAG']],
  ['Qdrant JS','IA','Cliente JavaScript para la base vectorial Qdrant.','@qdrant/js-client-rest','qdrant/qdrant-js',['Vectors','Search']],
  ['axios','Backend','Cliente HTTP basado en promesas para Node y web.','axios','axios/axios',['HTTP','Requests']],
  ['got','Backend','Cliente HTTP humano y potente para Node.js.','got','sindresorhus/got',['HTTP','Requests']],
  ['Zod OpenAPI','Backend','Genera documentación OpenAPI desde esquemas Zod.','@asteasolutions/zod-to-openapi','asteasolutions/zod-to-openapi',['OpenAPI','Zod']],
  ['jose','Backend','JWT, JWS y JWE para runtimes JavaScript.','jose','panva/jose',['JWT','Security']],
  ['nodemailer','Backend','Envía correos desde aplicaciones Node.js.','nodemailer','nodemailer/nodemailer',['Email','SMTP']],
  ['date-fns','DevTools','Utilidades de fecha modernas y modulares.','date-fns','date-fns/date-fns',['Dates','Utilities']],
  ['lodash','DevTools','Utilidades JavaScript probadas y modulares.','lodash','lodash/lodash',['Utilities','JavaScript']],
  ['nanoid','DevTools','Generador de IDs pequeños y seguros.','nanoid','ai/nanoid',['IDs','Security']],
  ['Sharp','DevTools','Procesamiento de imágenes de alto rendimiento.','sharp','lovell/sharp',['Images','Performance']],
  ['Cheerio','DevTools','Implementación jQuery rápida para scraping HTML.','cheerio','cheeriojs/cheerio',['HTML','Scraping']],
  ['Zxcvbn','DevTools','Estimador de fortaleza de contraseñas.','zxcvbn','dropbox/zxcvbn',['Security','Passwords']],
  ['tsx-cjs','DevTools','Compatibilidad CommonJS para flujos TypeScript.','tsx','privatenumber/tsx',['Runtime','Node']],
  ['Remeda','DevTools','Utilidades TypeScript-first inmutables y seguras.','remeda','remeda/remeda',['Utilities','TypeScript']],
  ['neverthrow','DevTools','Resultados type-safe para operaciones que pueden fallar.','neverthrow','supermacro/neverthrow',['Errors','TypeScript']],
  ['Effect','DevTools','Plataforma para programas TypeScript robustos.','effect','Effect-TS/effect',['Functional','Concurrency']],
  ['RxJS','DevTools','Programación reactiva con observables.','rxjs','ReactiveX/rxjs',['Reactive','Streams']],
  ['p-limit','DevTools','Limita la concurrencia de promesas.','p-limit','sindresorhus/p-limit',['Async','Concurrency']],
  ['node-cron','Backend','Programación de tareas con sintaxis cron.','node-cron','node-cron/node-cron',['Cron','Scheduling']],
  ['Undici','Backend','Cliente HTTP y fetch de alto rendimiento para Node.','undici','nodejs/undici',['HTTP','Fetch']],
]
export const libraries: Library[] = catalogue.slice(0,100).map(([name,category,description,npm,github,tags], index) => ({name,category,description,npm,github,tags,downloads:'Ver en npm',weeklyDownloads:100-index,stars:'Open source',color:palette[index%palette.length],featured:name==='Hono'}))
export const categories: Array<Category | 'Todas'> = ['Todas','Backend','Frontend','Datos','DevTools','IA','Testing']
